// <auto-generated />
using ExerciceFakeDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciceFakeDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240131145456_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExerciceFakeDb.Models.Monkey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Monkeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chen"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jean"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sawa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
